server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://47.107.157.20:3306/wann
    username: wanna
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      url: jdbc:mysql://47.107.157.20:3306/wann
      username: wann
      password: 123456
      max-active: 20


#
#mybatis:
#  #指定mybatis主配置文件的地址
#  config-location: classpath:mybatis/config/mybatis-config.xml