server:
  port: 8081

spring:
  datasource:
    mysql:
    url: jdbc:mysql://47.107.157.20:3306/wann
    username: wanna
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid1:
      url: jdbc:mysql://47.107.157.20:3306/wann
      username: wann
      password: 123456
      max-active: 20

    druid2:
      url: jdbc:mysql://47.107.157.20:3306/wann
      username: wann
      password: 123456
      max-active: 20

jedis:
  pool:
    host: 47.107.157.20 #host
    password: 123456 #password
    #port: 6379 #port
    timeout: 5000 #timeout
    # db: 0 #db
    max-active: 5000  # jedis最大活跃数目
    max-idle: 1000  # jedis最大保存idle状态对象数
    max-wait: 5000  # 最大等待时间
    testOnBorrow: true  # jedis调用borrowObject方法时，是否进行有效检查
    testOnReturn: true  # jedis调用returnObject方法时，是否进行有效检查



#
#mybatis:
#  #指定mybatis主配置文件的地址
#  config-location: classpath:mybatis/config/mybatis-config.xml